# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
    - id: run-unittests
      name: Run unittests
      entry: python -m unittest discover tests
      language: python
      pass_filenames: false